<?xml version="1.0" encoding="utf-8"?>
<Database Name="MyNotes" Class="MyNoteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dotnet-testbed;Initial Catalog=MyNotes;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyNotesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Note" Member="Notes">
    <Type Name="Note">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Entry" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>