<?xml version="1.0" encoding="utf-8"?><Database Name="VideoGames" Class="VideoGamesModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=VideoGames;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VideoGamesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GamePlatform" Member="GamePlatforms">
    <Type Name="GamePlatform">
      <Column Name="VideoGameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlatformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SKU" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockRemaining" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="GamePlatform_GameReview" Member="GameReviews" ThisKey="ID" OtherKey="GamePlatformID" Type="GameReview" />
      <Association Name="VideoGame_GamePlatform" Member="VideoGame" ThisKey="VideoGameID" OtherKey="ID" Type="VideoGame" IsForeignKey="true" />
      <Association Name="Platform_GamePlatform" Member="Platform" ThisKey="PlatformID" OtherKey="ID" Type="Platform" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VideoGame" Member="VideoGames">
    <Type Name="VideoGame">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ESRB" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="VideoGame_GamePlatform" Member="GamePlatforms" ThisKey="ID" OtherKey="VideoGameID" Type="GamePlatform" />
      <Association Name="Genre_VideoGame" Member="Genre" ThisKey="GenreID" OtherKey="ID" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameReview" Member="GameReviews">
    <Type Name="GameReview">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GamePlatformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewText" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="ReviewedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReviewedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="GamePlatform_GameReview" Member="GamePlatform" ThisKey="GamePlatformID" OtherKey="ID" Type="GamePlatform" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genres">
    <Type Name="Genre">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Genre_VideoGame" Member="VideoGames" ThisKey="ID" OtherKey="GenreID" Type="VideoGame" />
    </Type>
  </Table>
  <Table Name="dbo.Platform" Member="Platforms">
    <Type Name="Platform">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Platform_GamePlatform" Member="GamePlatforms" ThisKey="ID" OtherKey="PlatformID" Type="GamePlatform" />
    </Type>
  </Table>
</Database>