//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 10/31/2008 3:05:54 PM
namespace NorthWind.Business.EF.Miscellaneos
{
    
    /// <summary>
    /// There are no comments for XmlEntities in the schema.
    /// </summary>
    public partial class XmlEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new XmlEntities object using the connection string found in the 'XmlEntities' section of the application configuration file.
        /// </summary>
        public XmlEntities() : 
                base("name=XmlEntities", "XmlEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new XmlEntities object.
        /// </summary>
        public XmlEntities(string connectionString) : 
                base(connectionString, "XmlEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new XmlEntities object.
        /// </summary>
        public XmlEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "XmlEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Candidates in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Candidate> Candidates
        {
            get
            {
                if ((this._Candidates == null))
                {
                    this._Candidates = base.CreateQuery<Candidate>("[Candidates]");
                }
                return this._Candidates;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Candidate> _Candidates;
        /// <summary>
        /// There are no comments for Candidates in the schema.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }
    }
    /// <summary>
    /// There are no comments for xmldatatypeModel.Candidate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CandidateId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="xmldatatypeModel", Name="Candidate")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Candidate : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="candidateId">Initial value of CandidateId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Candidate CreateCandidate(int candidateId, string name)
        {
            Candidate candidate = new Candidate();
            candidate.CandidateId = candidateId;
            candidate.Name = name;
            return candidate;
        }
        /// <summary>
        /// There are no comments for Property CandidateId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId
        {
            get
            {
                return this._CandidateId;
            }
            set
            {
                this.OnCandidateIdChanging(value);
                this.ReportPropertyChanging("CandidateId");
                this._CandidateId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CandidateId");
                this.OnCandidateIdChanged();
            }
        }
        private int _CandidateId;
        partial void OnCandidateIdChanging(int value);
        partial void OnCandidateIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Resume in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private string Resume
        {
            get
            {
                return this._Resume;
            }
            set
            {
                this.OnResumeChanging(value);
                this.ReportPropertyChanging("Resume");
                this._Resume = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Resume");
                this.OnResumeChanged();
            }
        }
        private string _Resume;
        partial void OnResumeChanging(string value);
        partial void OnResumeChanged();
    }
}
