//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 10/9/2008 11:24:56 PM
namespace NorthWind.Business.EF.QueryView
{
    
    /// <summary>
    /// There are no comments for QueryViewEntities in the schema.
    /// </summary>
    public partial class QueryViewEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new QueryViewEntities object using the connection string found in the 'QueryViewEntities' section of the application configuration file.
        /// </summary>
        public QueryViewEntities() : 
                base("name=QueryViewEntities", "QueryViewEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new QueryViewEntities object.
        /// </summary>
        public QueryViewEntities(string connectionString) : 
                base(connectionString, "QueryViewEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new QueryViewEntities object.
        /// </summary>
        public QueryViewEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "QueryViewEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("[Customers]");
                }
                return this._Customers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for Actors in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Actors> Actors
        {
            get
            {
                if ((this._Actors == null))
                {
                    this._Actors = base.CreateQuery<Actors>("[Actors]");
                }
                return this._Actors;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Actors> _Actors;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for Actors in the schema.
        /// </summary>
        public void AddToActors(Actors actors)
        {
            base.AddObject("Actors", actors);
        }
    }
    /// <summary>
    /// There are no comments for QueryViewModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QueryViewModel", Name="Customer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Customer : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        /// <param name="hasAccount">Initial value of HasAccount.</param>
        public static Customer CreateCustomer(string customerID, string companyName, bool hasAccount)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CompanyName = companyName;
            customer.HasAccount = hasAccount;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this.ReportPropertyChanging("CustomerID");
                this._CustomerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CustomerID");
                this.OnCustomerIDChanged();
            }
        }
        private string _CustomerID;
        partial void OnCustomerIDChanging(string value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this.ReportPropertyChanging("CompanyName");
                this._CompanyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CompanyName");
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this.ReportPropertyChanging("ContactName");
                this._ContactName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactName");
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property HasAccount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAccount
        {
            get
            {
                return this._HasAccount;
            }
            set
            {
                this.OnHasAccountChanging(value);
                this.ReportPropertyChanging("HasAccount");
                this._HasAccount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HasAccount");
                this.OnHasAccountChanged();
            }
        }
        private bool _HasAccount;
        partial void OnHasAccountChanging(bool value);
        partial void OnHasAccountChanged();
    }
    /// <summary>
    /// There are no comments for QueryViewModel.Actors in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActorId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QueryViewModel", Name="Actors")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Actors : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Actors object.
        /// </summary>
        /// <param name="actorId">Initial value of ActorId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Actors CreateActors(int actorId, string name)
        {
            Actors actors = new Actors();
            actors.ActorId = actorId;
            actors.Name = name;
            return actors;
        }
        /// <summary>
        /// There are no comments for Property ActorId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ActorId
        {
            get
            {
                return this._ActorId;
            }
            set
            {
                this.OnActorIdChanging(value);
                this.ReportPropertyChanging("ActorId");
                this._ActorId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ActorId");
                this.OnActorIdChanged();
            }
        }
        private int _ActorId;
        partial void OnActorIdChanging(int value);
        partial void OnActorIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
}
