//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.ServiceModel.ServiceContractAttribute()]
public interface InterfaceMSMQ
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/InterfaceMSMQ/sendMessage")]
    void sendMessage(string strMessage);
}

public interface InterfaceMSMQChannel : InterfaceMSMQ, System.ServiceModel.IClientChannel
{
}

public partial class InterfaceMSMQProxy : System.ServiceModel.ClientBase<InterfaceMSMQ>, InterfaceMSMQ
{
    
    public InterfaceMSMQProxy()
    {
    }
    
    public InterfaceMSMQProxy(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InterfaceMSMQProxy(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceMSMQProxy(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceMSMQProxy(System.ServiceModel.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void sendMessage(string strMessage)
    {
        base.InnerProxy.sendMessage(strMessage);
    }
}
