#define CSUPMPERFOBJ                                        0
#define MSCSUPS_GET_PROFILE                                 2
#define MSCSUPS_GET_PROFILE_RATE                            4
#define MSCSUPS_GET_PROFILE_LATENCY                         6
#define MSCSUPS_CREATE_PROFILE                              8
#define MSCSUPS_CREATE_PROFILE_RATE                         10
#define MSCSUPS_CREATE_PROFILE_LATENCY                      12
#define MSCSUPS_DELETE_PROFILE                              14
#define MSCSUPS_DELETE_PROFILE_RATE                         16
#define MSCSUPS_DELETE_PROFILE_LATENCY                      18
#define MSCSUPS_MODIFY_PROFILE                              20
#define MSCSUPS_MODIFY_PROFILE_RATE                         22
#define MSCSUPS_MODIFY_PROFILE_LATENCY                      24
#define MSCSUPS_CACHE_OBJECTS                               26
#define MSCSUPS_CACHE_HIT_RATE                              28
#define MSCSUPS_CACHE_MISS_RATE                             30
#define MSCSUPS_BACKGROUND_THREAD_STATE                     32
#define MSCSUPS_FREE_ENTRY_LOOKUPS                          34
#define MSCSUPS_RETRY_LOGIC_SWITCH_TO_THREAD                36
#define MSCSUPS_LOCK_SWITCH_TO_THREAD                       38
#define CSOLEDB_ACTIVE_HEAP_COUNT                           40
#define CSOLEDB_ACTIVE_HEAP_COUNT_USING_SETCOUNTER          42
#define CSOLEDB_SWITCH_TO_THREAD                            44
#define ANSI_SQL_ACTIVE_CONN_COUNT                          46
#define ANSI_SQL_SWITCH_TO_THREAD                           48
#define UPMDTS_DATA_RECORDS_PS                              50
#define UPMDTS_DATA_RECORDS                                 52
#define UPMDTS_DATA_RECORDS_ERR                             54
