
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("ea1b232f-125b-41c4-8119-b0e778f96c90")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("NewPublisherModel", "FK_Author_Book", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NewPublisherModel.Author), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NewPublisherModel.Book), True)>

#End Region
Namespace NewPublisherModel
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NewPublisherEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new NewPublisherEntities object using the connection string found in the 'NewPublisherEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NewPublisherEntities", "NewPublisherEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NewPublisherEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NewPublisherEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NewPublisherEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NewPublisherEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Authors() As ObjectSet(Of Author)
            Get
                If (_Authors Is Nothing) Then
                    _Authors = MyBase.CreateObjectSet(Of Author)("Authors")
                End If
                Return _Authors
            End Get
        End Property
    
        Private _Authors As ObjectSet(Of Author)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Books() As ObjectSet(Of Book)
            Get
                If (_Books Is Nothing) Then
                    _Books = MyBase.CreateObjectSet(Of Book)("Books")
                End If
                Return _Books
            End Get
        End Property
    
        Private _Books As ObjectSet(Of Book)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToAuthors(ByVal author As Author)
            MyBase.AddObject("Authors", author)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToBooks(ByVal book As Book)
            MyBase.AddObject("Books", book)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NewPublisherModel", Name:="Author")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Author
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Author object.
        ''' </summary>
        ''' <param name="authorID">Initial value of the AuthorID property.</param>
        ''' <param name="lastName">Initial value of the LastName property.</param>
        ''' <param name="firstName">Initial value of the FirstName property.</param>
        Public Shared Function CreateAuthor(authorID As Global.System.Int32, lastName As Global.System.String, firstName As Global.System.String) As Author
            Dim author as Author = New Author
            author.AuthorID = authorID
            author.LastName = lastName
            author.FirstName = firstName
            Return author
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property AuthorID() As Global.System.Int32
            Get
                Return _AuthorID
            End Get
            Set
                If (_AuthorID <> Value) Then
                    OnAuthorIDChanging(value)
                    ReportPropertyChanging("AuthorID")
                    _AuthorID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("AuthorID")
                    OnAuthorIDChanged()
                End If
            End Set
        End Property
    
        Private _AuthorID As Global.System.Int32
        Private Partial Sub OnAuthorIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnAuthorIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LastName() As Global.System.String
            Get
                Return _LastName
            End Get
            Set
                OnLastNameChanging(value)
                ReportPropertyChanging("LastName")
                _LastName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LastName")
                OnLastNameChanged()
            End Set
        End Property
    
        Private _LastName As Global.System.String
        Private Partial Sub OnLastNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLastNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FirstName() As Global.System.String
            Get
                Return _FirstName
            End Get
            Set
                OnFirstNameChanging(value)
                ReportPropertyChanging("FirstName")
                _FirstName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("FirstName")
                OnFirstNameChanged()
            End Set
        End Property
    
        Private _FirstName As Global.System.String
        Private Partial Sub OnFirstNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirstNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property OnPanelDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _OnPanelDate
            End Get
            Set
                OnOnPanelDateChanging(value)
                ReportPropertyChanging("OnPanelDate")
                _OnPanelDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OnPanelDate")
                OnOnPanelDateChanged()
            End Set
        End Property
    
        Private _OnPanelDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnOnPanelDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnOnPanelDateChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NewPublisherModel", "FK_Author_Book", "Book")>
         Public Property Books() As EntityCollection(Of Book)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Book)("NewPublisherModel.FK_Author_Book", "Book")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Book)("NewPublisherModel.FK_Author_Book", "Book", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NewPublisherModel", Name:="Book")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Book
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Book object.
        ''' </summary>
        ''' <param name="bookISBN">Initial value of the BookISBN property.</param>
        ''' <param name="title">Initial value of the Title property.</param>
        ''' <param name="pages">Initial value of the Pages property.</param>
        ''' <param name="publishing_Date">Initial value of the Publishing_Date property.</param>
        ''' <param name="authorID">Initial value of the AuthorID property.</param>
        Public Shared Function CreateBook(bookISBN As Global.System.String, title As Global.System.String, pages As Global.System.Int32, publishing_Date As Global.System.DateTime, authorID As Global.System.Int32) As Book
            Dim book as Book = New Book
            book.BookISBN = bookISBN
            book.Title = title
            book.Pages = pages
            book.Publishing_Date = publishing_Date
            book.AuthorID = authorID
            Return book
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property BookISBN() As Global.System.String
            Get
                Return _BookISBN
            End Get
            Set
                If (_BookISBN <> Value) Then
                    OnBookISBNChanging(value)
                    ReportPropertyChanging("BookISBN")
                    _BookISBN = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("BookISBN")
                    OnBookISBNChanged()
                End If
            End Set
        End Property
    
        Private _BookISBN As Global.System.String
        Private Partial Sub OnBookISBNChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBookISBNChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Title() As Global.System.String
            Get
                Return _Title
            End Get
            Set
                OnTitleChanging(value)
                ReportPropertyChanging("Title")
                _Title = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Title")
                OnTitleChanged()
            End Set
        End Property
    
        Private _Title As Global.System.String
        Private Partial Sub OnTitleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnTitleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Pages() As Global.System.Int32
            Get
                Return _Pages
            End Get
            Set
                OnPagesChanging(value)
                ReportPropertyChanging("Pages")
                _Pages = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Pages")
                OnPagesChanged()
            End Set
        End Property
    
        Private _Pages As Global.System.Int32
        Private Partial Sub OnPagesChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnPagesChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Publishing_Date() As Global.System.DateTime
            Get
                Return _Publishing_Date
            End Get
            Set
                OnPublishing_DateChanging(value)
                ReportPropertyChanging("Publishing_Date")
                _Publishing_Date = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Publishing_Date")
                OnPublishing_DateChanged()
            End Set
        End Property
    
        Private _Publishing_Date As Global.System.DateTime
        Private Partial Sub OnPublishing_DateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnPublishing_DateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property AuthorID() As Global.System.Int32
            Get
                Return _AuthorID
            End Get
            Set
                OnAuthorIDChanging(value)
                ReportPropertyChanging("AuthorID")
                _AuthorID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("AuthorID")
                OnAuthorIDChanged()
            End Set
        End Property
    
        Private _AuthorID As Global.System.Int32
        Private Partial Sub OnAuthorIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnAuthorIDChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NewPublisherModel", "FK_Author_Book", "Author")>
        Public Property Author() As Author
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("NewPublisherModel.FK_Author_Book", "Author").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("NewPublisherModel.FK_Author_Book", "Author").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property AuthorReference() As EntityReference(Of Author)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("NewPublisherModel.FK_Author_Book", "Author")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Author)("NewPublisherModel.FK_Author_Book", "Author", value)
                End If
            End Set
        End Property

        #End Region
    End Class

    #End Region
    
End Namespace
