'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
'
Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Employee", [Namespace]:="http://schemas.datacontract.org/2004/07/DataBindinginSilverlightVB.Web")>  _
    Partial Public Class Employee
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private EmployeeIDField As Integer
        
        Private LastNameField As String
        
        Private FirstNameField As String
        
        Private TitleField As String
        
        Private TitleOfCourtesyField As String
        
        Private BirthDateField As System.Nullable(Of Date)
        
        Private HireDateField As System.Nullable(Of Date)
        
        Private AddressField As String
        
        Private CityField As String
        
        Private RegionField As String
        
        Private PostalCodeField As String
        
        Private CountryField As String
        
        Private HomePhoneField As String
        
        Private ExtensionField As String
        
        Private PhotoField As ServiceReference1.Binary
        
        Private NotesField As String
        
        Private ReportsToField As System.Nullable(Of Integer)
        
        Private PhotoPathField As String
        
        Private EmployeesField As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeID() As Integer
            Get
                Return Me.EmployeeIDField
            End Get
            Set
                If (Me.EmployeeIDField.Equals(value) <> true) Then
                    Me.EmployeeIDField = value
                    Me.RaisePropertyChanged("EmployeeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property TitleOfCourtesy() As String
            Get
                Return Me.TitleOfCourtesyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleOfCourtesyField, value) <> true) Then
                    Me.TitleOfCourtesyField = value
                    Me.RaisePropertyChanged("TitleOfCourtesy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property BirthDate() As System.Nullable(Of Date)
            Get
                Return Me.BirthDateField
            End Get
            Set
                If (Me.BirthDateField.Equals(value) <> true) Then
                    Me.BirthDateField = value
                    Me.RaisePropertyChanged("BirthDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property HireDate() As System.Nullable(Of Date)
            Get
                Return Me.HireDateField
            End Get
            Set
                If (Me.HireDateField.Equals(value) <> true) Then
                    Me.HireDateField = value
                    Me.RaisePropertyChanged("HireDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Property Region() As String
            Get
                Return Me.RegionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegionField, value) <> true) Then
                    Me.RegionField = value
                    Me.RaisePropertyChanged("Region")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalCodeField, value) <> true) Then
                    Me.PostalCodeField = value
                    Me.RaisePropertyChanged("PostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
        Public Property HomePhone() As String
            Get
                Return Me.HomePhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HomePhoneField, value) <> true) Then
                    Me.HomePhoneField = value
                    Me.RaisePropertyChanged("HomePhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=13)>  _
        Public Property Extension() As String
            Get
                Return Me.ExtensionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExtensionField, value) <> true) Then
                    Me.ExtensionField = value
                    Me.RaisePropertyChanged("Extension")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=14)>  _
        Public Property Photo() As ServiceReference1.Binary
            Get
                Return Me.PhotoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhotoField, value) <> true) Then
                    Me.PhotoField = value
                    Me.RaisePropertyChanged("Photo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=15)>  _
        Public Property Notes() As String
            Get
                Return Me.NotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NotesField, value) <> true) Then
                    Me.NotesField = value
                    Me.RaisePropertyChanged("Notes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=16)>  _
        Public Property ReportsTo() As System.Nullable(Of Integer)
            Get
                Return Me.ReportsToField
            End Get
            Set
                If (Me.ReportsToField.Equals(value) <> true) Then
                    Me.ReportsToField = value
                    Me.RaisePropertyChanged("ReportsTo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=17)>  _
        Public Property PhotoPath() As String
            Get
                Return Me.PhotoPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhotoPathField, value) <> true) Then
                    Me.PhotoPathField = value
                    Me.RaisePropertyChanged("PhotoPath")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property Employees() As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee)
            Get
                Return Me.EmployeesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmployeesField, value) <> true) Then
                    Me.EmployeesField = value
                    Me.RaisePropertyChanged("Employees")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Binary", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Linq")>  _
    Partial Public Class Binary
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private BytesField() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Bytes() As Byte()
            Get
                Return Me.BytesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BytesField, value) <> true) Then
                    Me.BytesField = value
                    Me.RaisePropertyChanged("Bytes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IMyService")>  _
    Public Interface IMyService
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMyService/GetByLastName", ReplyAction:="http://tempuri.org/IMyService/GetByLastNameResponse")>  _
        Function BeginGetByLastName(ByVal lastname As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetByLastName(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMyServiceChannel
        Inherits ServiceReference1.IMyService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetByLastNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MyServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IMyService)
        Implements ServiceReference1.IMyService
        
        Private onBeginGetByLastNameDelegate As BeginOperationDelegate
        
        Private onEndGetByLastNameDelegate As EndOperationDelegate
        
        Private onGetByLastNameCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event GetByLastNameCompleted As System.EventHandler(Of GetByLastNameCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_IMyService_BeginGetByLastName(ByVal lastname As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceReference1.IMyService.BeginGetByLastName
            Return MyBase.Channel.BeginGetByLastName(lastname, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_IMyService_EndGetByLastName(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee) Implements ServiceReference1.IMyService.EndGetByLastName
            Return MyBase.Channel.EndGetByLastName(result)
        End Function
        
        Private Function OnBeginGetByLastName(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim lastname As String = CType(inValues(0),String)
            Return CType(Me,ServiceReference1.IMyService).BeginGetByLastName(lastname, callback, asyncState)
        End Function
        
        Private Function OnEndGetByLastName(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee) = CType(Me,ServiceReference1.IMyService).EndGetByLastName(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetByLastNameCompleted(ByVal state As Object)
            If (Not (Me.GetByLastNameCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetByLastNameCompleted(Me, New GetByLastNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetByLastNameAsync(ByVal lastname As String)
            Me.GetByLastNameAsync(lastname, Nothing)
        End Sub
        
        Public Overloads Sub GetByLastNameAsync(ByVal lastname As String, ByVal userState As Object)
            If (Me.onBeginGetByLastNameDelegate Is Nothing) Then
                Me.onBeginGetByLastNameDelegate = AddressOf Me.OnBeginGetByLastName
            End If
            If (Me.onEndGetByLastNameDelegate Is Nothing) Then
                Me.onEndGetByLastNameDelegate = AddressOf Me.OnEndGetByLastName
            End If
            If (Me.onGetByLastNameCompletedDelegate Is Nothing) Then
                Me.onGetByLastNameCompletedDelegate = AddressOf Me.OnGetByLastNameCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetByLastNameDelegate, New Object() {lastname}, Me.onEndGetByLastNameDelegate, Me.onGetByLastNameCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As ServiceReference1.IMyService
            Return New MyServiceClientChannel(Me)
        End Function
        
        Private Class MyServiceClientChannel
            Inherits ChannelBase(Of ServiceReference1.IMyService)
            Implements ServiceReference1.IMyService
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of ServiceReference1.IMyService))
                MyBase.New(client)
            End Sub
            
            Public Function BeginGetByLastName(ByVal lastname As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceReference1.IMyService.BeginGetByLastName
                Dim _args((1) - 1) As Object
                _args(0) = lastname
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetByLastName", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetByLastName(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee) Implements ServiceReference1.IMyService.EndGetByLastName
                Dim _args((0) - 1) As Object
                Dim _result As System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee) = CType(MyBase.EndInvoke("GetByLastName", _args, result),System.Collections.ObjectModel.ObservableCollection(Of ServiceReference1.Employee))
                Return _result
            End Function
        End Class
    End Class
End Namespace
