//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 10/21/2008 5:01:45 PM
namespace NorthWind.Business.EF.Inheritance
{
    
    /// <summary>
    /// There are no comments for TPCEntities in the schema.
    /// </summary>
    public partial class TPCEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TPCEntities object using the connection string found in the 'TPCEntities' section of the application configuration file.
        /// </summary>
        public TPCEntities() : 
                base("name=TPCEntities", "TPCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TPCEntities object.
        /// </summary>
        public TPCEntities(string connectionString) : 
                base(connectionString, "TPCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TPCEntities object.
        /// </summary>
        public TPCEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TPCEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Location> Locations
        {
            get
            {
                if ((this._Locations == null))
                {
                    this._Locations = base.CreateQuery<Location>("[Locations]");
                }
                return this._Locations;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Location> _Locations;
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    }
    /// <summary>
    /// There are no comments for INHTPCModel.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="INHTPCModel", Name="Company")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Company : Location
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="locationId">Initial value of LocationId.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        /// <param name="president">Initial value of President.</param>
        public static Company CreateCompany(int locationId, string address, string companyName, string president)
        {
            Company company = new Company();
            company.LocationId = locationId;
            company.Address = address;
            company.CompanyName = companyName;
            company.President = president;
            return company;
        }
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this.ReportPropertyChanging("CompanyName");
                this._CompanyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CompanyName");
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property President in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string President
        {
            get
            {
                return this._President;
            }
            set
            {
                this.OnPresidentChanging(value);
                this.ReportPropertyChanging("President");
                this._President = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("President");
                this.OnPresidentChanged();
            }
        }
        private string _President;
        partial void OnPresidentChanging(string value);
        partial void OnPresidentChanged();
    }
    /// <summary>
    /// There are no comments for INHTPCModel.School in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="INHTPCModel", Name="School")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class School : Location
    {
        /// <summary>
        /// Create a new School object.
        /// </summary>
        /// <param name="locationId">Initial value of LocationId.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="schoolName">Initial value of SchoolName.</param>
        /// <param name="principal">Initial value of Principal.</param>
        public static School CreateSchool(int locationId, string address, string schoolName, string principal)
        {
            School school = new School();
            school.LocationId = locationId;
            school.Address = address;
            school.SchoolName = schoolName;
            school.Principal = principal;
            return school;
        }
        /// <summary>
        /// There are no comments for Property SchoolName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName
        {
            get
            {
                return this._SchoolName;
            }
            set
            {
                this.OnSchoolNameChanging(value);
                this.ReportPropertyChanging("SchoolName");
                this._SchoolName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SchoolName");
                this.OnSchoolNameChanged();
            }
        }
        private string _SchoolName;
        partial void OnSchoolNameChanging(string value);
        partial void OnSchoolNameChanged();
        /// <summary>
        /// There are no comments for Property Principal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Principal
        {
            get
            {
                return this._Principal;
            }
            set
            {
                this.OnPrincipalChanging(value);
                this.ReportPropertyChanging("Principal");
                this._Principal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Principal");
                this.OnPrincipalChanged();
            }
        }
        private string _Principal;
        partial void OnPrincipalChanging(string value);
        partial void OnPrincipalChanged();
    }
    /// <summary>
    /// There are no comments for INHTPCModel.Location in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="INHTPCModel", Name="Location")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::NorthWind.Business.EF.Inheritance.Company))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::NorthWind.Business.EF.Inheritance.School))]
    public abstract partial class Location : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this.ReportPropertyChanging("LocationId");
                this._LocationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationId");
                this.OnLocationIdChanged();
            }
        }
        private int _LocationId;
        partial void OnLocationIdChanging(int value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
    }
}
