//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 10/27/2008 5:16:08 PM
namespace InhQVForeign
{
    
    /// <summary>
    /// There are no comments for QvForeignEntities in the schema.
    /// </summary>
    public partial class QvForeignEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new QvForeignEntities object using the connection string found in the 'QvForeignEntities' section of the application configuration file.
        /// </summary>
        public QvForeignEntities() : 
                base("name=QvForeignEntities", "QvForeignEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new QvForeignEntities object.
        /// </summary>
        public QvForeignEntities(string connectionString) : 
                base(connectionString, "QvForeignEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new QvForeignEntities object.
        /// </summary>
        public QvForeignEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "QvForeignEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Persons in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Person> Persons
        {
            get
            {
                if ((this._Persons == null))
                {
                    this._Persons = base.CreateQuery<Person>("[Persons]");
                }
                return this._Persons;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Person> _Persons;
        /// <summary>
        /// There are no comments for Actors in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Actors> Actors
        {
            get
            {
                if ((this._Actors == null))
                {
                    this._Actors = base.CreateQuery<Actors>("[Actors]");
                }
                return this._Actors;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Actors> _Actors;
        /// <summary>
        /// There are no comments for Persons in the schema.
        /// </summary>
        public void AddToPersons(Person person)
        {
            base.AddObject("Persons", person);
        }
        /// <summary>
        /// There are no comments for Actors in the schema.
        /// </summary>
        public void AddToActors(Actors actors)
        {
            base.AddObject("Actors", actors);
        }
    }
    /// <summary>
    /// There are no comments for QvForeignModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QvForeignModel", Name="Customer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Customer : Person
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="accountNo">Initial value of AccountNo.</param>
        /// <param name="customerId">Initial value of CustomerId.</param>
        public static Customer CreateCustomer(int personId, string name, string accountNo, int customerId)
        {
            Customer customer = new Customer();
            customer.PersonId = personId;
            customer.Name = name;
            customer.AccountNo = accountNo;
            customer.CustomerId = customerId;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property AccountNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo
        {
            get
            {
                return this._AccountNo;
            }
            set
            {
                this.OnAccountNoChanging(value);
                this.ReportPropertyChanging("AccountNo");
                this._AccountNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AccountNo");
                this.OnAccountNoChanged();
            }
        }
        private string _AccountNo;
        partial void OnAccountNoChanging(string value);
        partial void OnAccountNoChanged();
        /// <summary>
        /// There are no comments for Property CustomerId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this._CustomerId;
            }
            set
            {
                this.OnCustomerIdChanging(value);
                this.ReportPropertyChanging("CustomerId");
                this._CustomerId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomerId");
                this.OnCustomerIdChanged();
            }
        }
        private int _CustomerId;
        partial void OnCustomerIdChanging(int value);
        partial void OnCustomerIdChanged();
    }
    /// <summary>
    /// There are no comments for QvForeignModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QvForeignModel", Name="Employee")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Employee : Person
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        /// <param name="employeeId">Initial value of EmployeeId.</param>
        public static Employee CreateEmployee(int personId, string name, string companyName, int employeeId)
        {
            Employee employee = new Employee();
            employee.PersonId = personId;
            employee.Name = name;
            employee.CompanyName = companyName;
            employee.EmployeeId = employeeId;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this.ReportPropertyChanging("CompanyName");
                this._CompanyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CompanyName");
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property EmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                this.OnEmployeeIdChanging(value);
                this.ReportPropertyChanging("EmployeeId");
                this._EmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeId");
                this.OnEmployeeIdChanged();
            }
        }
        private int _EmployeeId;
        partial void OnEmployeeIdChanging(int value);
        partial void OnEmployeeIdChanged();
    }
    /// <summary>
    /// There are no comments for QvForeignModel.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QvForeignModel", Name="Person")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::InhQVForeign.Customer))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::InhQVForeign.Employee))]
    public abstract partial class Person : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this.ReportPropertyChanging("PersonId");
                this._PersonId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PersonId");
                this.OnPersonIdChanged();
            }
        }
        private int _PersonId;
        partial void OnPersonIdChanging(int value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for QvForeignModel.Actors in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActorId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QvForeignModel", Name="Actors")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Actors : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Actors object.
        /// </summary>
        /// <param name="actorId">Initial value of ActorId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Actors CreateActors(int actorId, string name)
        {
            Actors actors = new Actors();
            actors.ActorId = actorId;
            actors.Name = name;
            return actors;
        }
        /// <summary>
        /// There are no comments for Property ActorId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ActorId
        {
            get
            {
                return this._ActorId;
            }
            set
            {
                this.OnActorIdChanging(value);
                this.ReportPropertyChanging("ActorId");
                this._ActorId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ActorId");
                this.OnActorIdChanged();
            }
        }
        private int _ActorId;
        partial void OnActorIdChanging(int value);
        partial void OnActorIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
}
