//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TwoTPTModel", "FK_GunSmith_Company", "Company", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TwoTPT.Company), "GunSmith", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TwoTPT.GunSmith))]

// Original file name:
// Generation date: 11/19/2008 5:19:03 PM
namespace TwoTPT
{
    
    /// <summary>
    /// There are no comments for TwoTPTEntities in the schema.
    /// </summary>
    public partial class TwoTPTEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TwoTPTEntities object using the connection string found in the 'TwoTPTEntities' section of the application configuration file.
        /// </summary>
        public TwoTPTEntities() : 
                base("name=TwoTPTEntities", "TwoTPTEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TwoTPTEntities object.
        /// </summary>
        public TwoTPTEntities(string connectionString) : 
                base(connectionString, "TwoTPTEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TwoTPTEntities object.
        /// </summary>
        public TwoTPTEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TwoTPTEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Contact> Contact
        {
            get
            {
                if ((this._Contact == null))
                {
                    this._Contact = base.CreateQuery<Contact>("[Contact]");
                }
                return this._Contact;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Contact> _Contact;
        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Location> Location
        {
            get
            {
                if ((this._Location == null))
                {
                    this._Location = base.CreateQuery<Location>("[Location]");
                }
                return this._Location;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Location> _Location;
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public void AddToContact(Contact contact)
        {
            base.AddObject("Contact", contact);
        }
        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        public void AddToLocation(Location location)
        {
            base.AddObject("Location", location);
        }
    }
    /// <summary>
    /// There are no comments for TwoTPTModel.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TwoTPTModel", Name="Company")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Company : Location
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="locationId">Initial value of LocationId.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="phone">Initial value of Phone.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        public static Company CreateCompany(int locationId, string address, string phone, string companyName)
        {
            Company company = new Company();
            company.LocationId = locationId;
            company.Address = address;
            company.Phone = phone;
            company.CompanyName = companyName;
            return company;
        }
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this.ReportPropertyChanging("CompanyName");
                this._CompanyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CompanyName");
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for GunSmith in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TwoTPTModel", "FK_GunSmith_Company", "GunSmith")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GunSmith> GunSmith
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GunSmith>("TwoTPTModel.FK_GunSmith_Company", "GunSmith");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GunSmith>("TwoTPTModel.FK_GunSmith_Company", "GunSmith", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TwoTPTModel.Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ContactId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TwoTPTModel", Name="Contact")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::TwoTPT.GunSmith))]
    public partial class Contact : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="contactId">Initial value of ContactId.</param>
        /// <param name="contactName">Initial value of ContactName.</param>
        /// <param name="email">Initial value of Email.</param>
        public static Contact CreateContact(int contactId, string contactName, string email)
        {
            Contact contact = new Contact();
            contact.ContactId = contactId;
            contact.ContactName = contactName;
            contact.Email = email;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property ContactId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactId
        {
            get
            {
                return this._ContactId;
            }
            set
            {
                this.OnContactIdChanging(value);
                this.ReportPropertyChanging("ContactId");
                this._ContactId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContactId");
                this.OnContactIdChanged();
            }
        }
        private int _ContactId;
        partial void OnContactIdChanging(int value);
        partial void OnContactIdChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this.ReportPropertyChanging("ContactName");
                this._ContactName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ContactName");
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
    }
    /// <summary>
    /// There are no comments for TwoTPTModel.GunSmith in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ContactId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TwoTPTModel", Name="GunSmith")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GunSmith : Contact
    {
        /// <summary>
        /// Create a new GunSmith object.
        /// </summary>
        /// <param name="contactId">Initial value of ContactId.</param>
        /// <param name="contactName">Initial value of ContactName.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="isCertified">Initial value of IsCertified.</param>
        public static GunSmith CreateGunSmith(int contactId, string contactName, string email, bool isCertified)
        {
            GunSmith gunSmith = new GunSmith();
            gunSmith.ContactId = contactId;
            gunSmith.ContactName = contactName;
            gunSmith.Email = email;
            gunSmith.IsCertified = isCertified;
            return gunSmith;
        }
        /// <summary>
        /// There are no comments for Property IsCertified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCertified
        {
            get
            {
                return this._IsCertified;
            }
            set
            {
                this.OnIsCertifiedChanging(value);
                this.ReportPropertyChanging("IsCertified");
                this._IsCertified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsCertified");
                this.OnIsCertifiedChanged();
            }
        }
        private bool _IsCertified;
        partial void OnIsCertifiedChanging(bool value);
        partial void OnIsCertifiedChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TwoTPTModel", "FK_GunSmith_Company", "Company")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Company Company
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Company>("TwoTPTModel.FK_GunSmith_Company", "Company").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Company>("TwoTPTModel.FK_GunSmith_Company", "Company").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Company> CompanyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Company>("TwoTPTModel.FK_GunSmith_Company", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Company>("TwoTPTModel.FK_GunSmith_Company", "Company", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TwoTPTModel.Location in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TwoTPTModel", Name="Location")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::TwoTPT.Company))]
    public partial class Location : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="locationId">Initial value of LocationId.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="phone">Initial value of Phone.</param>
        public static Location CreateLocation(int locationId, string address, string phone)
        {
            Location location = new Location();
            location.LocationId = locationId;
            location.Address = address;
            location.Phone = phone;
            return location;
        }
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this.ReportPropertyChanging("LocationId");
                this._LocationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationId");
                this.OnLocationIdChanged();
            }
        }
        private int _LocationId;
        partial void OnLocationIdChanging(int value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
    }
}
