<?xml version="1.0" encoding="utf-8"?>
<Database Name="MetaTags" Class="MetaDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=MetaTags;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MetaTagsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Page" Member="Pages">
    <Type Name="Page">
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Page_MetaData" Member="MetaDatas" ThisKey="PageId" OtherKey="PageId" Type="MetaData" />
    </Type>
  </Table>
  <Table Name="dbo.MetaData" Member="MetaDatas">
    <Type Name="MetaData">
      <Column Name="MetaDataId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Page_MetaData" Member="Page" ThisKey="PageId" OtherKey="PageId" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
</Database>