//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaSelfModel", "FK_MediaCategory_MediaCategory", "MediaCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NorthWind.Business.EF.SelfReferencing.MediaCategory), "MediaCategory1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NorthWind.Business.EF.SelfReferencing.MediaCategory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MediaSelfModel", "MediaInCategories", "Media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NorthWind.Business.EF.SelfReferencing.Media), "MediaCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NorthWind.Business.EF.SelfReferencing.MediaCategory))]

// Original file name:
// Generation date: 11/8/2008 12:16:04 PM
namespace NorthWind.Business.EF.SelfReferencing
{
    
    /// <summary>
    /// There are no comments for MediaSelfRefEntities in the schema.
    /// </summary>
    public partial class MediaSelfRefEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MediaSelfRefEntities object using the connection string found in the 'MediaSelfRefEntities' section of the application configuration file.
        /// </summary>
        public MediaSelfRefEntities() : 
                base("name=MediaSelfRefEntities", "MediaSelfRefEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaSelfRefEntities object.
        /// </summary>
        public MediaSelfRefEntities(string connectionString) : 
                base(connectionString, "MediaSelfRefEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaSelfRefEntities object.
        /// </summary>
        public MediaSelfRefEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MediaSelfRefEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Medias in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Media> Medias
        {
            get
            {
                if ((this._Medias == null))
                {
                    this._Medias = base.CreateQuery<Media>("[Medias]");
                }
                return this._Medias;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Media> _Medias;
        /// <summary>
        /// There are no comments for MediaCategories in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MediaCategory> MediaCategories
        {
            get
            {
                if ((this._MediaCategories == null))
                {
                    this._MediaCategories = base.CreateQuery<MediaCategory>("[MediaCategories]");
                }
                return this._MediaCategories;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MediaCategory> _MediaCategories;
        /// <summary>
        /// There are no comments for Medias in the schema.
        /// </summary>
        public void AddToMedias(Media media)
        {
            base.AddObject("Medias", media);
        }
        /// <summary>
        /// There are no comments for MediaCategories in the schema.
        /// </summary>
        public void AddToMediaCategories(MediaCategory mediaCategory)
        {
            base.AddObject("MediaCategories", mediaCategory);
        }
    }
    /// <summary>
    /// There are no comments for MediaSelfModel.Article in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MediaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaSelfModel", Name="Article")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Article : Media
    {
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="mediaId">Initial value of MediaId.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Article CreateArticle(int mediaId, string title)
        {
            Article article = new Article();
            article.MediaId = mediaId;
            article.Title = title;
            return article;
        }
        /// <summary>
        /// There are no comments for Property ArticleContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleContent
        {
            get
            {
                return this._ArticleContent;
            }
            set
            {
                this.OnArticleContentChanging(value);
                this.ReportPropertyChanging("ArticleContent");
                this._ArticleContent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ArticleContent");
                this.OnArticleContentChanged();
            }
        }
        private string _ArticleContent;
        partial void OnArticleContentChanging(string value);
        partial void OnArticleContentChanged();
    }
    /// <summary>
    /// There are no comments for MediaSelfModel.Media in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MediaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaSelfModel", Name="Media")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::NorthWind.Business.EF.SelfReferencing.Article))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::NorthWind.Business.EF.SelfReferencing.Video))]
    public abstract partial class Media : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// There are no comments for Property MediaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaId
        {
            get
            {
                return this._MediaId;
            }
            set
            {
                this.OnMediaIdChanging(value);
                this.ReportPropertyChanging("MediaId");
                this._MediaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MediaId");
                this.OnMediaIdChanged();
            }
        }
        private int _MediaId;
        partial void OnMediaIdChanging(int value);
        partial void OnMediaIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for MediaCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaSelfModel", "MediaInCategories", "MediaCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<MediaCategory> MediaCategory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<MediaCategory>("MediaSelfModel.MediaInCategories", "MediaCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<MediaCategory>("MediaSelfModel.MediaInCategories", "MediaCategory", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaSelfModel.MediaCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaSelfModel", Name="MediaCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MediaCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MediaCategory object.
        /// </summary>
        /// <param name="categoryId">Initial value of CategoryId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static MediaCategory CreateMediaCategory(int categoryId, string name)
        {
            MediaCategory mediaCategory = new MediaCategory();
            mediaCategory.CategoryId = categoryId;
            mediaCategory.Name = name;
            return mediaCategory;
        }
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this.ReportPropertyChanging("CategoryId");
                this._CategoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryId");
                this.OnCategoryIdChanged();
            }
        }
        private int _CategoryId;
        partial void OnCategoryIdChanging(int value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for SubCategories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaSelfModel", "FK_MediaCategory_MediaCategory", "MediaCategory1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<MediaCategory> SubCategories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaSelfModel", "FK_MediaCategory_MediaCategory", "MediaCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MediaCategory Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MediaCategory> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MediaCategory>("MediaSelfModel.FK_MediaCategory_MediaCategory", "MediaCategory", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Medias in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MediaSelfModel", "MediaInCategories", "Media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Media> Medias
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Media>("MediaSelfModel.MediaInCategories", "Media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Media>("MediaSelfModel.MediaInCategories", "Media", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MediaSelfModel.Video in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MediaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MediaSelfModel", Name="Video")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Video : Media
    {
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="mediaId">Initial value of MediaId.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Video CreateVideo(int mediaId, string title)
        {
            Video video = new Video();
            video.MediaId = mediaId;
            video.Title = title;
            return video;
        }
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private global::System.Nullable<int> _Rating;
        partial void OnRatingChanging(global::System.Nullable<int> value);
        partial void OnRatingChanged();
    }
}
