//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_ClientApp.MyRefQtrwiseSales {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sales", Namespace="http://schemas.datacontract.org/2004/07/WCF_ServiceQtrwsieSales")]
    [System.SerializableAttribute()]
    public partial class Sales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Q1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Q2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Q3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Q4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Q1 {
            get {
                return this.Q1Field;
            }
            set {
                if ((this.Q1Field.Equals(value) != true)) {
                    this.Q1Field = value;
                    this.RaisePropertyChanged("Q1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Q2 {
            get {
                return this.Q2Field;
            }
            set {
                if ((this.Q2Field.Equals(value) != true)) {
                    this.Q2Field = value;
                    this.RaisePropertyChanged("Q2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Q3 {
            get {
                return this.Q3Field;
            }
            set {
                if ((this.Q3Field.Equals(value) != true)) {
                    this.Q3Field = value;
                    this.RaisePropertyChanged("Q3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Q4 {
            get {
                return this.Q4Field;
            }
            set {
                if ((this.Q4Field.Equals(value) != true)) {
                    this.Q4Field = value;
                    this.RaisePropertyChanged("Q4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyRefQtrwiseSales.IQtrwiseSales")]
    public interface IQtrwiseSales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQtrwiseSales/GetSalesDetsils", ReplyAction="http://tempuri.org/IQtrwiseSales/GetSalesDetsilsResponse")]
        WPF_ClientApp.MyRefQtrwiseSales.Sales[] GetSalesDetsils();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQtrwiseSalesChannel : WPF_ClientApp.MyRefQtrwiseSales.IQtrwiseSales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QtrwiseSalesClient : System.ServiceModel.ClientBase<WPF_ClientApp.MyRefQtrwiseSales.IQtrwiseSales>, WPF_ClientApp.MyRefQtrwiseSales.IQtrwiseSales {
        
        public QtrwiseSalesClient() {
        }
        
        public QtrwiseSalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QtrwiseSalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QtrwiseSalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QtrwiseSalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPF_ClientApp.MyRefQtrwiseSales.Sales[] GetSalesDetsils() {
            return base.Channel.GetSalesDetsils();
        }
    }
}
